version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile # Production Dockerfile
      args:
        PORT: 3030
        REACT_APP_BACKEND: http://localhost:9000
        REACT_APP_STAT_URL: http://localhost:9100
        REACT_APP_COUNTRY_NAME: "Seychelles"
    ports:
      - "9030:3030"
